// This file is used by the Flutter tool to register Flutter web plugins.
// Please do not edit this file manually.

import 'package:flutter_web_plugins/flutter_web_plugins.dart';

void registerPlugins([final Registrar? pluginRegistrar]) {
  // Add any web-specific plugin registration here if needed
}